### ISSUE TITLE
Wrap asynchronous API interactions with AsyncResult interface

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/sdr-client#133]
This is what dor-services-client already does to protect downstream applications from having to worry about SDR API client/server interactions. Port this approach to sdr-client.

See: 
* [Documentation](https://github.com/sul-dlss/dor-services-client#asynchronous-results)
* [API](https://github.com/sul-dlss/dor-services-client/blob/db4e3396fb206da488a7cfffcad890730a278fc6/lib/dor/services/client/versioned_service.rb#L13-L16)
* [Implementation](https://github.com/sul-dlss/dor-services-client/blob/08f6000ff87e0e2453c7d31c718ecac634688144/lib/dor/services/client/async_result.rb)

**Comment by justinlittman** [comment]
Upon further discussion with @jcoyne, it was determined that this approach is potentially problematic. A deposit may take an indeterminate amount of time; exceeding the timeout does not necessarily indicate that deposit failed.

closing in favor of https://github.com/sul-dlss/happy-heron/issues/202
