### ISSUE TITLE
Handle request DRO when no structural is provided

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-client#134]
Presently it raises:
```
NoMethodError: undefined method `contains' for nil:NilClass
```

because it does `request_dro.structural.contains.map`

See https://app.honeybadger.io/projects/77112/faults/68952572

**Comment by mjgiarlo** [comment]
@jcoyne looks like you may already be working on this, so I moved to in progress

**Comment by jcoyne** [comment]
Nope, I'm not working on this.

**Comment by mjgiarlo** [comment]
@jcoyne ok, thanks
