### ISSUE TITLE
Add a way to update an item's APO via the CLI

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-client#184]
The user should be able to provide a command such as:
```
sdr --service-url https://sdr-api-server:3000 update --admin-policy 'druid:bk123gh4567'
```

And the APO should be updated. Please add documentation in the README.

**Comment by mjgiarlo** [comment]
@jcoyne A couple questions:

1. Should the item's version in cocina be incremented? 
2. Does it need to be in, or to be put into, any particular workflow state?

**Comment by jcoyne** [comment]
@mjgiarlo not for this ticket.
