### ISSUE TITLE
Add a way to update an item's access rights via the CLI

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-client#188]
The user should be able to provide a command such as:
```
sdr --service-url https://sdr-api-server:3000 update --access-view stanford-only --access-download location-based --access-location music'
```

And the access rights should be updated. Please add documentation in the README.

**Comment by mjgiarlo** [comment]
@jcoyne @andrewjbtw I have a few questions about this issue:

1. The example above covers three of the five access-control-related parts of access (`view`, `download`, `location`) and leaves two out (`controlledDigitalLending`, `embargo`). I assume for now we are intentionally leaving embargo out. Should CDL be supported here? (I assume so.)
1. Should this feature:
    1. *replace* what the item already has set for access settings (wiping out values not provided);
    2. *patch in* the provided values, and assume the user isn't going to create combinations of settings that aren't valid (in which case they will get an error in return); or
    3. *require* all of these flags all the time?

**Comment by jcoyne** [comment]
@mjgiarlo if you specify cdl, then can it force view to 'stanford', download to 'none', and location to null:

https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L495-L521

**Comment by mjgiarlo** [comment]
@jcoyne Yeah, I'm wondering about what flags to accept, what to enforce/validate, etc. 

The easiest approach is to allow users to specify any of all of the four non-embargo access settings and assume the user isn't going to give bogus settings... and if they do, sdr-api will bark at them. Maybe I'll go with that until/unless someone says otherwise.

**Comment by jcoyne** [comment]
That seems reasonable.

**Comment by mjgiarlo** [comment]
@jcoyne @andrewjbtw should this also set access for all the files in the object? Or just the object-level access?
