### ISSUE TITLE
Fix expected require path

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-client#46]
Currently we have to do this:
```
gem 'sdr-client', '~> 0.4.0', require: 'sdr_client'
```

it would be better if we didn't have to have the `require: 'sdr_client'`

**Comment by justinlittman** [comment]
To fix this, would we use the same strategy as lyber-core? https://github.com/sul-dlss/lyber-core/tree/master/lib

**Comment by jcoyne** [comment]
@justinlittman right.
