### ISSUE TITLE
Runtime Error for Deposit.run Method

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/sdr-client#98]
When `SdrClient::Deposit.run` is invoked with the files parameter, a runtime error occurs:

```
There was an error with your request: {"id":"bad_request","message":"#/co
mponents/schemas/RequestFile missing required parameters: version"}
```

This bug blocks https://github.com/sul-dlss/infrastructure-integration-test/issues/24

**Comment by justinlittman** [comment]
Fixed by #99.
